### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by keveri** [Lepovirta/pikkuwiki#1]
What is this about? How to use?

**Comment by jpallari** [comment]
This a utility for managing a personal wiki that uses minimal markup. Everything is based on text files. Only markup is a link syntax for linking to other documents. The utility provides ways to query pages for links to other pages, which can be opened directly using text editors.

I'll add a README soon. :-)

**Comment by jpallari** [comment]
Things to answer:
- What is this?
- What is it for?
- What are the core features?
- How do I install this?
- How do I use this?

**Comment by jpallari** [comment]
Done! ba9bf24273ce5068b4db2204c21d62569a5f1d8b
